import { Injectable } from '@nestjs/common';
import * as fs from 'fs';
import * as path from 'path';

@Injectable()
export class ScaffoldService {

  generate(projectName: string, blueprint: any) {

    const basePath = path.join(
      process.cwd(),
      'src/generated',
      projectName
    );

    this.ensureDir(basePath);

    // =========================
    // CREATE MODULES
    // =========================
    blueprint.modules.forEach((module: string) => {
      this.createModule(basePath, module);
    });

    // =========================
    // CREATE ROUTES FILE
    // =========================
    this.createRoutes(basePath, blueprint.api);

    // =========================
    // CREATE README
    // =========================
    fs.writeFileSync(
      path.join(basePath, 'README.md'),
      this.generateReadme(projectName, blueprint)
    );

    return {
      ok: true,
      path: basePath,
      modules: blueprint.modules.length,
    };
  }

  // =========================
  // CREATE MODULE STRUCTURE
  // =========================
  private createModule(basePath: string, module: string) {

    const modulePath = path.join(basePath, module);

    this.ensureDir(modulePath);

    fs.writeFileSync(
      path.join(modulePath, `${module}.controller.ts`),
      `export class ${this.capitalize(module)}Controller {}`
    );

    fs.writeFileSync(
      path.join(modulePath, `${module}.service.ts`),
      `export class ${this.capitalize(module)}Service {}`
    );
  }

  // =========================
  // ROUTES FILE
  // =========================
  private createRoutes(basePath: string, api: string[]) {

    fs.writeFileSync(
      path.join(basePath, 'routes.txt'),
      api.join('\n')
    );
  }

  // =========================
  // README
  // =========================
  private generateReadme(name: string, blueprint: any) {

    return `
# ${name.toUpperCase()}

## Type
${blueprint.type}

## Modules
${blueprint.modules.join('\n')}

## API
${blueprint.api.join('\n')}

## Generated by KVRAT.ai 🚀
`;
  }

  // =========================
  // HELPERS
  // =========================
  private ensureDir(dir: string) {
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
  }

  private capitalize(str: string) {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }
}